### PR TITLE
Use new params system for envelope values

### PR DESCRIPTION
**Pull request by lazzarello**
This code adds Arc support to control each voice's envelopes like an LFO. Can go forwards or backwards. Based on previous work in #4

### CODE REVIEW

**Comment by lazzarello** [comment]
Whelp, I seem to have introduced a weird bug where changing the scale in the params menu makes the screen go blank until I move an arc encoder, then the Norns encoders and keys get stuck in sample rate edit mode.

**Comment by aidanreilly** [comment]
I basically have no way to test this. maybe reach out on the forums to see if someone with an arc can help you test?

**Comment by lazzarello** [comment]
In this case, the test would be to run the script without an arc and determine that it continues to do what we both expect. Does that sound reasonable?

**Comment by aidanreilly** [comment]
Sure thing. Just let me know when you're ready.

**Comment by lazzarello** [comment]
Can you run this branch on your device? You'll have to SSH to the local system and clone my fork...or copy + paste everything into Maiden.

**Comment by aidanreilly** [comment]
Yup. Tonight.

**Comment by aidanreilly** [comment]
BTW - have you tested arc control + midi mapping? Can both controls happen simultaneously without error?

**Comment by aidanreilly** [comment]
Hey, I'm really sorry, but i'm not going to merge this. I'm planning an update that includes LFO animation on chord voicing and i'm pretty sure this stuff would just get broken and I'd be unable to maintain. Your code (as far as I can see) is totally fine and good though. 

Maybe an opportunity to keep this fork seperate and rename this arcsine or something cool like that? again, i'm genuinely sorry - hopefully you understand. I'm chuffed that people are using this, and would love to see this get taken in new directions.

Thanks,
Aidan

**Comment by lazzarello** [comment]
That's cool. This is why we have forks! I'm playing a show this weekend using my Arc fork.

**Comment by aidanreilly** [comment]
Ace! Would love to hear it if you record it. Share it on the lines thread if you do.

**Pull request closed without merging**
