### PR TITLE
[WIP] Arc enable

### PR DESCRIPTION
**Pull request by lazzarello**
Work from [a thread on the Lines forum](https://llllllll.co/t/sines/39292/79) to add Arc support, controlling the speed and direction of each envelope.

### CODE REVIEW

**Comment by aidanreilly** [comment]
FYI - I'm refactoring a good chunk of the code to make full use of standard norns params. Every available param will be moved to a standard norns param type. I'm going to focus on this before looking at this merge. I'll probably push the params updates to main first, and then ask you to review and adjust your PR accordingly. 

I'm working these changes on the develop branch. I'm also considering reworking the GUI along the lines of what justmat has done with his LARC scipt, which has really nice progesssive disclosure style GUI pop ups.

**Comment by aidanreilly** [comment]
BTW, the refactor on develop branch opens up env attack, decay, and bias as individual params per voice. still a WIP. 

Also, do you think cents detuning is useful? I wonder would it be more straight forward to just display a hz value and allow the user to tune up and down the freq in hz. maybe hz isn't as useful from a musician's perspective.

**Comment by lazzarello** [comment]
> BTW, the refactor on develop branch opens up env attack, decay, and bias as individual params per voice. still a WIP.
> 
> Also, do you think cents detuning is useful? I wonder would it be more straight forward to just display a hz value and allow the user to tune up and down the freq in hz. maybe hz isn't as useful from a musician's perspective.

I do think cents detuning is useful. I like how FM can get into the harsh realm when the frequency ratios aren't whole numbers. Hz isn't as useful for scales and supercollider/musicutils makes generating scales so easy.

Regarding your refactor, I think I can move a lot of the Arc logic out of the main script and into a module, which will make merging changes easier. I haven't touched any of the UI functions.

**Comment by aidanreilly** [comment]
Yes - not a big thing to keep cents and it is useful as you say. Hopefully will have this ready for the end of the week. If I get all the param stuff in, I'll see about making the GUI a bit nicer too.

**Comment by lazzarello** [comment]
Obsolete by #9

**Pull request closed without merging**
