### PR TITLE
OSC input will make `screen_dirty`

### PR DESCRIPTION
**Pull request by okyeron**
Update so OSC input will make `screen_dirty` and trigger display refresh

### CODE REVIEW

**Comment by p3r7** [comment]
can you cite specific params for which receiving OSC events didn't trig a screen refresh?

(it worked for me, at least for volume & pan params, when i've toyed w/ a m4l script that sends OSC)

indeed, we mark screen dirty through param callbacks: `encoder/16n change > param callback > screen dirty`
OSC messages should trigger the same chain of events: `OSC message > param callback > screen dirty`

it's great that this one-liner fixes things for you, but this may be a brute-force way to solve a bad behaviour that may be local to only a few params.

**Comment by okyeron** [comment]
I was looking at directly at params and at the main screen of sines. Sending the appropriate osc param messages was changing the values in params, but not on the main screen of sines.

I'll check again now that I've worked around the virtual faders not responding as expected... Removed the screen_dirty and I do see display refresh on the main sines page.

EDIT for clarification - so yes this is probably not needed for the main params...

But - I added a "master volume" slider in the touchosc template for `output_level` and it does not update.

**Comment by p3r7** [comment]
> Removed the screen_dirty and I do see display refresh on the main sines page.

do you mean you managed to get the screen to update from osc message w/ the patch of this PR off?

**Comment by okyeron** [comment]
> do you mean you managed to get the screen to update from osc message w/ the patch of this PR off?

Clarifying:

Without this patch, screen updates DO work for vol/env/etc.

"Master Vol" aka `output_level` does not get updated on the Sines main screen without this patch.

**Comment by p3r7** [comment]
oh ok, gotcha.

**Comment by aireilly** [comment]
Sorry, been busy! @p3r7 or @okyeron I have no way of testing this (or time!). Can we get someone else to test this?

**Comment by p3r7** [comment]
i kinda want to merge this.

but by thinking again about it, i guess that we also have an issue w/ changing the global volume param from the param menu.
i suppose it would not trigger a screen redraw either...

i wonder if there is a way to kill both birds w/ one stone?

**Comment by aireilly** [comment]
@p3r7 I'm totally ambivalent, so if you can make this work and think it's useful go ahead. As long as we don't interfere with existing hardware controller usage :shrug:

**Comment by aireilly** [comment]
Closing this. Feel free to rework/reopen if you want to get this merged.

**Pull request closed without merging**
